### ISSUE TITLE
Rename `html-from-bemjson` techs

### ISSUE THREAD

**Issue by blond** [enb-bem/enb-xjst#50]
* Rename `html-from-bemjson` tech to `bemjson-to-html`.
* Rename `html-from-bemjson-i18n` tech to `bemjson-to-html-i18n`.

**Comment by tormozz48** [comment]
@blond 

Данная задача частично устарела т.к. насколько я помню мы перенесли `html-from-bemjson-i18n` технологию в enb-bem-i18n.

Вопрос при переименовании `html-from-bemjson` в `bemjson-to-html` старую технологию нужно объявить deprecated или вообще удалить?

**Comment by tormozz48** [comment]
т.е. не удалить а просто переименовать без фолбека

**Comment by blond** [comment]
Просто переименовать, т.к. уже были изменения ломающие обратную совместимость. Объявлять устаревшими логично в НЕ мажорных релизах.
