### ISSUE TITLE
BEMTREE: includeVow option

### ISSUE THREAD

**Issue by blond** [enb-bem/enb-xjst#71]
Add an option to merge BEMTREE-bundle with code of vow module.

**Comment by tadatuta** [comment]
Please refer to https://github.com/bem/bem-core/issues/1095

**Comment by blond** [comment]
@tadatuta `enb-xjst` for `bem-bl` ;) 

@tormozz48 [ported](#68) this from https://github.com/enb-bem/enb-bemxjst/issues/33

**Comment by tadatuta** [comment]
`bem-bl` and async BEMTREE? for whom? o_0

**Comment by blond** [comment]
@tadatuta https://github.com/enb-bem/enb-xjst/blob/master/test/fixtures/bemtree/i-bem.bemtree.xjst

**Comment by tavriaforever** [comment]
Maybe there is no one user who will use it with `bem-bl`
