### ISSUE TITLE
Uninformative error message

### ISSUE THREAD

**Issue by blond** [enb-bem/enb-xjst#79]
**Versions:**

* `Node.js@10.37`
* `bem-bl@2.9.0`
* `enb-xjst@1.2.0`
* `bem-bl-xjst@2.1.4`

**BEMHTML code:**

```js
elem attach, content: [{
    block: 'w-attach',
    name: this.ctx.file.fullName,
    author: this.ctx.attach['user_name] <- не хватает второй кавычки
}]
```

**Error message:**

```
SyntaxError: Unexpected token

    at Object.parse (native)
    at BEMHTMLParser.<anonymous> ...
make: *** [bem-make] Error 1
```

**Comment by blond** [comment]
Не смог воспроизвести.

Попробуй обновиться до `v2.0.0-beta2`.

/сс @birhoff

**Comment by birhoff** [comment]
Обновился, проблема осталась, может попробуем вместе на моем проекте, если в чистых условиях не воспроизводится.

**Comment by blond** [comment]
Проект перевели, проблема не воспрозвелась.
